# Tomcat
server:
  port: 9201
  servlet:
    session:
      timeout: 120m
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.10.136:2333/smgt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: smgt
    password: heuSSS321.002
mybatis:
  typeAliasesPackage: com.wbz.system
  mapperLocations: classpath:mapper/**/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
minio:
  url: http://150.158.10.136:9000
  accessKey: minio
  secretKey: minio123.
