# Tomcat
server:
  port: 9201
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.10.136:2333/smgt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    url: jdbc:mysql://127.0.0.1:3306/fa?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: smgt
    password: heuSSS321.002
mybatis:
  typeAliasesPackage: com.wbz.system
  mapperLocations: classpath:mapper/**/*.xml

